#################################
# Minimal smooth config for i3 + Kitty + Neovim
#################################

backend = "xrender";
vsync = false;
use-damage = true;
unredir-if-possible = true;

shadow = false;
#shadow-radius = 12;
#shadow-opacity = 0.75;
#shadow-offset-x = -15;
#shadow-offset-y = -15;

fading = false;

corner-radius = 8;

opacity-rule = [
  "85:class_g = 'kitty'",
  "95:class_g = 'Alacritty'",
  "95:class_g = 'code-oss'",
  "80:class_g = 'Rofi'"
];

detect-client-opacity = true;
detect-rounded-corners = true;

log-level = "warn";
